
default:

clean:
	make clean -C nanafy-symbol
	make clean -C nanafy-local-relocation
	make clean -C nanafy-relocation
	make clean -C nanafy-memory

test:
	make test -C nanafy-symbol
	make test -C nanafy-local-relocation
	make test -C nanafy-relocation
	make test -C nanafy-memory
