#define DEFINE_NANAFY_LIST(name, type)\
DEFINE_INIT_NANAFY_LIST(name, type)\
DEFINE_SET_NANAFY_LIST(name, type)\
DEFINE_GET_NANAFY_LIST(name, type)\
DEFINE_ADD_NANAFY_LIST(name, type)\
DEFINE_NANAFY_LIST_LENGTH(name, type)\
DEFINE_COPY_NANAFY_LIST(name, type)\
DEFINE_EXTEND_NANAFY_LIST(name, type)\
DEFINE_FREE_NANAFY_LIST(name, type)\
DEFINE_HAS_NANAFY_LIST_MARGIN(name, type)

#define DECLARE_NANAFY_LIST(name, type)\
DEFINE_NANAFY_LIST_TYPE(name, type)\
DECLARE_INIT_NANAFY_LIST(name, type)\
DECLARE_SET_NANAFY_LIST(name, type)\
DECLARE_GET_NANAFY_LIST(name, type)\
DECLARE_ADD_NANAFY_LIST(name, type)\
DECLARE_NANAFY_LIST_LENGTH(name, type)\
DECLARE_COPY_NANAFY_LIST(name, type)\
DECLARE_EXTEND_NANAFY_LIST(name, type)\
DECLARE_FREE_NANAFY_LIST(name, type)\
DECLARE_HAS_NANAFY_LIST_MARGIN(name, type)
