
default:

clean:
	rm -f nanafy-list.h

nanafy-list.h: src/nanafy-list.h src/nanafy-list-type.h src/init-nanafy-list.h src/get-nanafy-list.h src/set-nanafy-list.h src/add-nanafy-list.h src/nanafy-list-length.h src/copy-nanafy-list.h src/extend-nanafy-list.h src/free-nanafy-list.h src/has-nanafy-list-margin.h
	cat src/nanafy-list.h src/nanafy-list-type.h src/init-nanafy-list.h src/get-nanafy-list.h src/set-nanafy-list.h src/add-nanafy-list.h src/nanafy-list-length.h src/copy-nanafy-list.h src/extend-nanafy-list.h src/free-nanafy-list.h src/has-nanafy-list-margin.h > nanafy-list.h
