
default:

clean:
	rm -f nanafy-array.h

nanafy-array.h: src/nanafy-array.h src/nanafy-array-type.h src/init-nanafy-array.h src/get-nanafy-array.h src/set-nanafy-array.h src/nanafy-array-length.h src/clear-nanafy-array.h src/copy-nanafy-array.h src/extend-nanafy-array.h src/free-nanafy-array.h
	cat src/nanafy-array.h src/nanafy-array-type.h src/init-nanafy-array.h src/get-nanafy-array.h src/set-nanafy-array.h src/nanafy-array-length.h src/clear-nanafy-array.h src/copy-nanafy-array.h src/extend-nanafy-array.h src/free-nanafy-array.h > nanafy-array.h
